### ISSUE TITLE
Merging covid and provincial dataframes

### ISSUE THREAD

**Issue by gvanloon** [Panchamy/TIL6010#14]
I’ve been struggling for quite some time already to combine the dataframes on the covid and mobility data.
The covid data has three rows per province per date, and the mobility data has only one (see attachments). 
I thought I could resample for the dates, but now pandas has resampled all the provinces per date, so all the provinces have the exact same data.

![image](https://user-images.githubusercontent.com/90392568/139529750-43f0b7a4-c7ea-4e10-bda6-6c58e8db9d2f.png)
![image](https://user-images.githubusercontent.com/90392568/139529760-a63e1e95-3b88-4538-93ef-dc6008076bcb.png)

This is what I've got up til now, but it's still not working properly.
Could someone help me out? The csv's are added below

[2021_NL_Region_Mobility_Report.csv](https://github.com/Panchamy/TIL6010/files/7446314/2021_NL_Region_Mobility_Report.csv)
[RIVM_NL_provincial.csv](https://github.com/Panchamy/TIL6010/files/7446315/RIVM_NL_provincial.csv)

[2020_NL_Region_Mobility_Report.csv](https://github.com/Panchamy/TIL6010/files/7446313/2020_NL_Region_Mobility_Report.csv)

**Comment by Panchamy** [comment]
You don't have to use all the three types of covid data. Pick one that's interesting for your data story!

**Comment by gvanloon** [comment]
Okay! But I'd still like to know how to turn the three rows into columns! I've been trying for quite some time and I'd like to know if there's some trick or anything to fix this :)

**Comment by nguyenthientin** [comment]
maybe [this link](https://pandas.pydata.org/docs/user_guide/reshaping.html) can help?

**Comment by gvanloon** [comment]
Yes thanks! That'll help figure it out :)
