### ISSUE TITLE
Assignment 2, exercise 3

### ISSUE THREAD

**Issue by wkoopal** [Panchamy/TIL6010#8]
Hi Panchamy,

I have some trouble with exercise 3 of assignment 2. I don't no if this is a right way to work with the given definition. Could you give me some tips? I attached my work.

 
![Knipsel1](https://user-images.githubusercontent.com/89969194/134656802-c4ae91c3-3828-4289-9173-4ad6a7fc968e.JPG)
![image](https://user-images.githubusercontent.com/89969194/134656959-c8f338d3-39e3-490c-95ba-8e6a3fbbc021.png)

**Comment by Panchamy** [comment]
There are several problems with this code. The function can have an input as follows:
df_province_selected, 'parks_percent_change_from_baseline', 2020, 'mean'
