### ISSUE TITLE
Error .dt accessor with datetimelike values | assignment 2, exercise 3 

### ISSUE THREAD

**Issue by dckole** [Panchamy/TIL6010#9]
Hi, 

I'm having some trubble with exercise 3 from assignment 2. I have written the calculate_statistic function, but when I'm trying to print the results, I get the following error: 

![image](https://user-images.githubusercontent.com/47820477/135268674-51ea11bd-27b7-4815-89c4-42ca07a36752.png)

I think the error is somewhere in the code where I define the the date column, which looks like this:

![image](https://user-images.githubusercontent.com/47820477/135268798-7a46e800-7c57-4b51-bceb-9479e44f533b.png)

On StackOverflow I found that that the datetime is still a str/object type instead of dype, but how to fix this problem and how to put that into code is still unclear for me. 

I hope you can help me out, thanks a lot in advance!

**Comment by Panchamy** [comment]
You can use pandas to_datetime function to convert your date to date time type. Right now you are assigning the data['date'] to year which only extracts the year. 

https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html
